name: sizelabs_upc_reader
description: UPC Reader by Sizelabs
version: 0.0.5

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  qr_mobile_vision: ^4.1.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.sizelabs.sizelabs_upc_reader
        pluginClass: SizelabsUpcPlugin
      ios:
        pluginClass: SizelabsUpcPlugin
